default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  host: <%= ENV["DB_HOST"] || "127.0.0.1" %>
  username: <%= ENV["POSTGRES_USER"] || ENV["DB_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] ||ENV["DB_PASS"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 50 } %>

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  primary: &primary_production
    <<: *default
    database: demo_production
    username: demo
    password: <%= ENV["DEMO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: demo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: demo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: demo_production_cable
    migrations_paths: db/cable_migrate
